name: Build Boost

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Detect Machine
      run: |
        ls /usr/local/opt/runner/settings/instancename
    - name: Run script
      run: |
        sudo spctl --master-disable
        chmod +x ./run.sh
        ./run.sh
